- hosts: local
  vars:
    variations:
      - version: 5.5
        server: apache
        full: false
      - version: 5.6
        server: apache
        full: false
      - version: 5.5
        server: apache
        full: true
        magento_version: 1.0.0-beta
      - version: 5.6
        server: apache
        full: true
        magento_version: 1.0.0-beta
  tasks:
  - name: prepare directory
    shell: "mkdir -p ../{% if item.full %}full{% else %}platform{% endif %}/{{ item.version }}/{{ item.server }}"
    with_items: "{{ variations }}"
  - name: generate Dockerfile
    template:
      src: "Dockerfile.j2"
      dest: "../{% if item.full %}full{% else %}platform{% endif %}/{{ item.version }}/{{ item.server }}/Dockerfile"
    with_items: "{{ variations }}"
  - name: build image
    shell: "docker build --pull --force-rm -t chadrien/magento2:{{ item.version }}-{{ item.server }}{% if item.full %}-full-{{ item.magento_version }}{% endif %} ."
    args:
      chdir: "../{% if item.full %}full{% else %}platform{% endif %}/{{ item.version }}/{{ item.server }}"
    with_items: "{{ variations }}"
    tags:
      - building
  - name: push image
    shell: "docker push chadrien/magento2:{{ item.version }}-{{ item.server }}{% if item.full %}-full-{{ item.magento_version }}{% endif %}"
    with_items: "{{ variations }}"
    tags:
      - building